### ISSUE TITLE
Cannot create Python 3 virtualenv in alppaca checkout

### ISSUE THREAD

**Issue by snordhausen** [ImmobilienScout24/alppaca#13]
It seems we a being bitten by https://github.com/pypa/virtualenv/issues/740, the file setup.cfg is picked line up as config file by some tool. What triggers the error is the following line in the file:

```
release = 0%{?dist}
```

As a result, various Python 3 stuff fails, e.g. setting up a new virtualenv:

```
$ rm -rf venv3; virtualenv -p /usr/bin/python3 venv3
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in venv3/bin/python3
Also creating executable in venv3/bin/python
Installing setuptools, pip...
  Complete output from command /home/snordhaus...ca/venv3/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking setuptools
Downloading/unpacking pip
Installing collected packages: setuptools, pip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/wheel.py", line 140, in move_wheel_files
    scheme = distutils_scheme(name, user=user, home=home, root=root)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/locations.py", line 147, in distutils_scheme
    d.parse_config_files()
  File "/usr/lib/python3.4/distutils/dist.py", line 401, in parse_config_files
    val = parser.get(section,opt)
  File "/usr/lib/python3.4/configparser.py", line 773, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 374, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 423, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%{?dist}'
```

Once the offending line is commented out, everything works as expected.

**Comment by mriehl** [comment]
What's wrong with `release = 0` (or removing it altogether)? I found out what it does once and as far as I remember it's kind of useless and not worth the hassle. Some kind of interpolation that never gets used I think.

**Comment by esc** [comment]
@mriehl you arguments are convincing. In fact I don't even understand what purpose this serves.

**Comment by schlomo** [comment]
The `%{dist}` suffix is an old RHEL habit. For example, they mark RHEL6 packages with `.el6` and RHEL5 with `.el5`.

If it helps somebody, then +1 for removing it.

**Comment by range** [comment]
Genau. Das ?dist kann man da wohl rauswerfen. Machen und das issue hier schließen.

**Comment by snordhausen** [comment]
Fixed.

As Schlomo said, the version format changed from "alppaca-1.0_123-0.el6.noarch" to "alppaca-1.0_123-0.noarch".
