### ISSUE TITLE
Alppaca dies while fetching credentials with wrong assume_role configuration

### ISSUE THREAD

**Issue by 5nafu** [ImmobilienScout24/alppaca#18]
Alppaca dies while fetching credentials with wrong assume_role configuration:

```
Oct 14 14:15:38 <host> Cannot start Alppaca
  #012Traceback (most recent call last):
  #012  File "/usr/lib/python2.6/site-packages/alppaca/main.py", line 43, in run_scheduler_and_webserver
  #012    Scheduler(credentials, credentials_provider).refresh_credentials()
  #012  File "/usr/lib/python2.6/site-packages/alppaca/scheduler.py", line 58, in refresh_credentials
  #012    cached_credentials = self.credentials_provider.get_credentials_for_all_roles()
  #012  File "/usr/lib/python2.6/site-packages/alppaca/assume_role.py", line 28, in get_credentials_for_all_roles
  #012    return self.get_credentials_for_assumed_role(access_key, secret_key, token)
  #012  File "/usr/lib/python2.6/site-packages/alppaca/assume_role.py", line 45, in get_credentials_for_assumed_role
  #012    response = conn.assume_role(role_arn=self.role_to_assume, role_session_name=self.get_session_name())
  #012  File "/usr/lib/python2.6/site-packages/boto/sts/connection.py", line 384, in assume_role
  #012    return self.get_object('AssumeRole', params, AssumedRole, verb='POST')
  #012  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1208, in get_object
  #012    raise self.ResponseError(response.status, response.reason, body)
  #012BotoServerError: BotoServerError: 403 Forbidden
  #012<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  #012  <Error>
  #012    <Type>Sender</Type>
  #012    <Code>AccessDenied</Code>
  #012    <Message>User arn:aws:sts::123456789:assumed-role/<rolename>/1.2.3.4 is not authorized to perform: sts:AssumeRole on resource: FILL_ME</Message>
  #012  </Error>
  #012  <RequestId>[...]</RequestId>
  #012</ErrorResponse>
```

**Comment by snordhausen** [comment]
Can you please try again with the most recent version of Alppaca? If it still fails, please specify what "wrong configuration" means in your case.

**Comment by schlomo** [comment]
Well, in the stack trace we see an error that Boto threw up. The Message clearly says that there is a permission issue.

I would suggest the following expected behaviour if the assume_role feature fails:
- Do not return any credentials at all, same like if AFP does not have a role for this machine
- Write the Code and Message to the error log
- Alpacca should nevertheless start and run because the error condition might be resolved and then it should start to work without any user intervention (IMHO Alpacca should always start and try to recover functionality by itself)
